[package]
name = "proj"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.1.0"
bio-seq = "0.10.0"
clap = { version = "4.2.7", features = ["derive"] }
derive_more = "0.99.17"
itertools = "0.10.5"
xxhash-rust = {version = "0.8.6", features = ["xxh3", "const_xxh3"] }

[profile.release-with-debug]
inherits = "release"
debug = true

[dev-dependencies]
assert_cmd = "2.0.11"
predicates = "3.0.3"
