[package]
name = "duplicate-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bio = "1.6.0"
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.0"
env_logger = "0.11.3"
log = "0.4.22"
rayon = "1.10.0"
serde = "1.0.203"
serde_json = "1.0.118"
spoa = { git = "https://github.com/olliecheng/spoa-rs" }

[[bin]]
name = "duplicate-tools"
