[package]
name = "proj"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bio = "1.1.0"
clap = { version = "4.2.7", features = ["derive"] }
lazy_static = "1.4.0"
memchr = "2.5.0"
petgraph = "0.6.3"
xxhash-rust = {version = "0.8.6", features = ["xxh3", "const_xxh3"] }

[profile.release-with-debug]
inherits = "release"
debug = true

[dev-dependencies]
assert_cmd = "2.0.11"
criterion = "0.5.1"
petgraph = "0.6.3"
predicates = "3.0.3"
pretty_assertions = "1.3.0"

[[bench]]
name = "benchmark"
harness = false
