[package]
name = "consensus"
version = "0.1.0"
edition = "2021"

[dependencies]
bio = "1.6.0"
clap = { version = "4.5.7", features = ["derive"] }
csv = "1.3.0"
serde = "1.0.203"
serde_json = "1.0.118"
